# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Tue Aug 11 22:40:58 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(497, 495)
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.urlEdit = QtGui.QLineEdit(Form)
        self.urlEdit.setGeometry(QtCore.QRect(120, 20, 351, 31))
        self.urlEdit.setObjectName(_fromUtf8("urlEdit"))
        self.propertyWidget = QtGui.QTabWidget(Form)
        self.propertyWidget.setGeometry(QtCore.QRect(40, 70, 431, 321))
        self.propertyWidget.setObjectName(_fromUtf8("propertyWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.contentFile = QtGui.QLineEdit(self.tab)
        self.contentFile.setGeometry(QtCore.QRect(100, 20, 221, 31))
        self.contentFile.setObjectName(_fromUtf8("contentFile"))
        self.contentFileBrowser = QtGui.QPushButton(self.tab)
        self.contentFileBrowser.setGeometry(QtCore.QRect(330, 20, 75, 31))
        self.contentFileBrowser.setObjectName(_fromUtf8("contentFileBrowser"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.type = QtGui.QLineEdit(self.tab)
        self.type.setGeometry(QtCore.QRect(101, 70, 191, 31))
        self.type.setObjectName(_fromUtf8("type"))
        self.base64 = QtGui.QToolButton(self.tab)
        self.base64.setGeometry(QtCore.QRect(296, 67, 41, 31))
        self.base64.setObjectName(_fromUtf8("base64"))
        self.base62 = QtGui.QToolButton(self.tab)
        self.base62.setGeometry(QtCore.QRect(350, 70, 41, 31))
        self.base62.setObjectName(_fromUtf8("base62"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.contentContent = QtGui.QPlainTextEdit(self.tab)
        self.contentContent.setGeometry(QtCore.QRect(90, 140, 311, 141))
        self.contentContent.setObjectName(_fromUtf8("contentContent"))
        self.propertyWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 381, 22))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.headersKeyEdit = QtGui.QLineEdit(self.layoutWidget)
        self.headersKeyEdit.setObjectName(_fromUtf8("headersKeyEdit"))
        self.horizontalLayout_3.addWidget(self.headersKeyEdit)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.headersValueEdit = QtGui.QLineEdit(self.layoutWidget)
        self.headersValueEdit.setObjectName(_fromUtf8("headersValueEdit"))
        self.horizontalLayout_3.addWidget(self.headersValueEdit)
        self.headersTabelView = QtGui.QTableView(self.tab_2)
        self.headersTabelView.setGeometry(QtCore.QRect(20, 90, 381, 192))
        self.headersTabelView.setObjectName(_fromUtf8("headersTabelView"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 221, 25))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.headersAdd = QtGui.QPushButton(self.layoutWidget1)
        self.headersAdd.setObjectName(_fromUtf8("headersAdd"))
        self.horizontalLayout_4.addWidget(self.headersAdd)
        self.headersRemove = QtGui.QPushButton(self.layoutWidget1)
        self.headersRemove.setObjectName(_fromUtf8("headersRemove"))
        self.horizontalLayout_4.addWidget(self.headersRemove)
        self.propertyWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.layoutWidget2 = QtGui.QWidget(self.tab_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 10, 381, 22))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_8 = QtGui.QLabel(self.layoutWidget2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.paramKeyEidt = QtGui.QLineEdit(self.layoutWidget2)
        self.paramKeyEidt.setObjectName(_fromUtf8("paramKeyEidt"))
        self.horizontalLayout_2.addWidget(self.paramKeyEidt)
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.paramValueEidt = QtGui.QLineEdit(self.layoutWidget2)
        self.paramValueEidt.setObjectName(_fromUtf8("paramValueEidt"))
        self.horizontalLayout_2.addWidget(self.paramValueEidt)
        self.tableView = QtGui.QTableView(self.tab_3)
        self.tableView.setGeometry(QtCore.QRect(20, 90, 381, 192))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.layoutWidget3 = QtGui.QWidget(self.tab_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 40, 221, 25))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.paramAdd = QtGui.QPushButton(self.layoutWidget3)
        self.paramAdd.setObjectName(_fromUtf8("paramAdd"))
        self.horizontalLayout_5.addWidget(self.paramAdd)
        self.paramRemove = QtGui.QPushButton(self.layoutWidget3)
        self.paramRemove.setObjectName(_fromUtf8("paramRemove"))
        self.horizontalLayout_5.addWidget(self.paramRemove)
        self.propertyWidget.addTab(self.tab_3, _fromUtf8(""))
        self.propertyButton = QtGui.QPushButton(Form)
        self.propertyButton.setGeometry(QtCore.QRect(310, 450, 75, 23))
        self.propertyButton.setObjectName(_fromUtf8("propertyButton"))
        self.closeButton = QtGui.QPushButton(Form)
        self.closeButton.setGeometry(QtCore.QRect(400, 450, 75, 23))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.layoutWidget4 = QtGui.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(40, 400, 431, 25))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.getButton = QtGui.QPushButton(self.layoutWidget4)
        self.getButton.setObjectName(_fromUtf8("getButton"))
        self.horizontalLayout.addWidget(self.getButton)
        self.postButton = QtGui.QPushButton(self.layoutWidget4)
        self.postButton.setObjectName(_fromUtf8("postButton"))
        self.horizontalLayout.addWidget(self.postButton)
        self.putButton = QtGui.QPushButton(self.layoutWidget4)
        self.putButton.setObjectName(_fromUtf8("putButton"))
        self.horizontalLayout.addWidget(self.putButton)
        self.deleteButton = QtGui.QPushButton(self.layoutWidget4)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.horizontalLayout.addWidget(self.deleteButton)

        self.retranslateUi(Form)
        self.propertyWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "url:", None))
        self.label_2.setText(_translate("Form", "file:", None))
        self.contentFileBrowser.setText(_translate("Form", "browser", None))
        self.label_4.setText(_translate("Form", "Ctt:", None))
        self.base64.setText(_translate("Form", "base64", None))
        self.base62.setText(_translate("Form", "base64", None))
        self.label_9.setText(_translate("Form", "type:", None))
        self.propertyWidget.setTabText(self.propertyWidget.indexOf(self.tab), _translate("Form", "Content", None))
        self.label_5.setText(_translate("Form", "Key", None))
        self.label_6.setText(_translate("Form", "value", None))
        self.headersAdd.setText(_translate("Form", "add", None))
        self.headersRemove.setText(_translate("Form", "remove", None))
        self.propertyWidget.setTabText(self.propertyWidget.indexOf(self.tab_2), _translate("Form", "Headers", None))
        self.label_8.setText(_translate("Form", "Key", None))
        self.label_7.setText(_translate("Form", "value", None))
        self.paramAdd.setText(_translate("Form", "add", None))
        self.paramRemove.setText(_translate("Form", "remove", None))
        self.propertyWidget.setTabText(self.propertyWidget.indexOf(self.tab_3), _translate("Form", "Paramenter", None))
        self.propertyButton.setText(_translate("Form", "Property", None))
        self.closeButton.setText(_translate("Form", "Close", None))
        self.getButton.setText(_translate("Form", "GET", None))
        self.postButton.setText(_translate("Form", "POST", None))
        self.putButton.setText(_translate("Form", "PUT", None))
        self.deleteButton.setText(_translate("Form", "DELETE", None))

        self.paramentersTableView = QtGui.QTableView(self.tab_3)
        self.paramentersTableView.setGeometry(QtCore.QRect(20, 90, 381, 192))
        self.paramentersTableView.setObjectName(_fromUtf8("paramentersTableView"))
        self.MyInitUi()

    def MyInitUi(self):

        #headers tabelView
        self.headersTabelModel = QtGui.QStandardItemModel()
        self.headersTabelModel.setHorizontalHeaderItem(0, QtGui.QStandardItem("key"))
        self.headersTabelModel.setHorizontalHeaderItem(1, QtGui.QStandardItem("value"))

        self.headersTabelView.setModel(self.headersTabelModel)
        self.headersTabelView.horizontalHeader().setResizeMode(0, QtGui.QHeaderView.Fixed)
        self.headersTabelView.horizontalHeader().setResizeMode(1, QtGui.QHeaderView.Fixed)
        self.headersTabelView.setColumnWidth(0, 190)
        self.headersTabelView.setColumnWidth(1, 189)
        self.headersTabelView.verticalHeader().show()
        self.headersTabelView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.headersTabelView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)


        #paramenters tabelView
        self.paramentersTabelModel = QtGui.QStandardItemModel()
        self.paramentersTabelModel.setHorizontalHeaderItem(0, QtGui.QStandardItem("key"))
        self.paramentersTabelModel.setHorizontalHeaderItem(1, QtGui.QStandardItem("value"))

        self.paramentersTableView.setModel(self.paramentersTabelModel)
        self.paramentersTableView.horizontalHeader().setResizeMode(0, QtGui.QHeaderView.Fixed)
        self.paramentersTableView.horizontalHeader().setResizeMode(1, QtGui.QHeaderView.Fixed)
        self.paramentersTableView.setColumnWidth(0, 190)
        self.paramentersTableView.setColumnWidth(1, 189)
        self.paramentersTableView.verticalHeader().show()
        self.paramentersTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.paramentersTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)