# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Jul 20 20:59:45 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(497, 495)
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.urlEdit = QtGui.QLineEdit(Form)
        self.urlEdit.setGeometry(QtCore.QRect(120, 20, 351, 31))
        self.urlEdit.setObjectName(_fromUtf8("urlEdit"))
        self.propertyWidget = QtGui.QTabWidget(Form)
        self.propertyWidget.setGeometry(QtCore.QRect(40, 70, 431, 321))
        self.propertyWidget.setObjectName(_fromUtf8("propertyWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.contentFile = QtGui.QLineEdit(self.tab)
        self.contentFile.setGeometry(QtCore.QRect(100, 20, 221, 31))
        self.contentFile.setObjectName(_fromUtf8("contentFile"))
        self.contentFileBrowser = QtGui.QPushButton(self.tab)
        self.contentFileBrowser.setGeometry(QtCore.QRect(330, 20, 75, 31))
        self.contentFileBrowser.setObjectName(_fromUtf8("contentFileBrowser"))
        self.contentContent = QtGui.QTextEdit(self.tab)
        self.contentContent.setGeometry(QtCore.QRect(100, 70, 301, 211))
        self.contentContent.setObjectName(_fromUtf8("contentContent"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.propertyWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.headersTableWidget = QtGui.QTableWidget(self.tab_2)
        self.headersTableWidget.setGeometry(QtCore.QRect(20, 80, 381, 201))
        self.headersTableWidget.setShowGrid(True)
        self.headersTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.headersTableWidget.setRowCount(5)
        self.headersTableWidget.setColumnCount(2)
        self.headersTableWidget.setObjectName(_fromUtf8("headersTableWidget"))
        self.headersTableWidget.horizontalHeader().setVisible(False)
        self.headersTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.headersTableWidget.horizontalHeader().setDefaultSectionSize(173)
        self.headersTableWidget.horizontalHeader().setHighlightSections(False)
        self.headersTableWidget.verticalHeader().setVisible(False)
        self.headersTableWidget.verticalHeader().setHighlightSections(True)
        self.headersTableWidget.verticalHeader().setSortIndicatorShown(True)
        self.headersTableWidget.verticalHeader().setStretchLastSection(True)
        self.splitter = QtGui.QSplitter(self.tab_2)
        self.splitter.setGeometry(QtCore.QRect(30, 40, 225, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.headersAdd = QtGui.QPushButton(self.splitter)
        self.headersAdd.setObjectName(_fromUtf8("headersAdd"))
        self.headersRemove = QtGui.QPushButton(self.splitter)
        self.headersRemove.setObjectName(_fromUtf8("headersRemove"))
        self.headersChange = QtGui.QPushButton(self.splitter)
        self.headersChange.setObjectName(_fromUtf8("headersChange"))
        self.widget = QtGui.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(20, 10, 381, 22))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.headersKeyEdit = QtGui.QLineEdit(self.widget)
        self.headersKeyEdit.setObjectName(_fromUtf8("headersKeyEdit"))
        self.horizontalLayout_3.addWidget(self.headersKeyEdit)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.headersValueEdit = QtGui.QLineEdit(self.widget)
        self.headersValueEdit.setObjectName(_fromUtf8("headersValueEdit"))
        self.horizontalLayout_3.addWidget(self.headersValueEdit)
        self.propertyWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.paramTableWidget = QtGui.QTableWidget(self.tab_3)
        self.paramTableWidget.setGeometry(QtCore.QRect(20, 80, 381, 201))
        self.paramTableWidget.setShowGrid(True)
        self.paramTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.paramTableWidget.setRowCount(5)
        self.paramTableWidget.setColumnCount(2)
        self.paramTableWidget.setObjectName(_fromUtf8("paramTableWidget"))
        self.paramTableWidget.horizontalHeader().setVisible(False)
        self.paramTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.paramTableWidget.horizontalHeader().setDefaultSectionSize(173)
        self.paramTableWidget.horizontalHeader().setHighlightSections(False)
        self.paramTableWidget.verticalHeader().setVisible(False)
        self.paramTableWidget.verticalHeader().setHighlightSections(True)
        self.paramTableWidget.verticalHeader().setSortIndicatorShown(True)
        self.paramTableWidget.verticalHeader().setStretchLastSection(True)
        self.splitter_2 = QtGui.QSplitter(self.tab_3)
        self.splitter_2.setGeometry(QtCore.QRect(30, 40, 225, 23))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.paramAdd = QtGui.QPushButton(self.splitter_2)
        self.paramAdd.setObjectName(_fromUtf8("paramAdd"))
        self.paramRemove = QtGui.QPushButton(self.splitter_2)
        self.paramRemove.setObjectName(_fromUtf8("paramRemove"))
        self.paramChange = QtGui.QPushButton(self.splitter_2)
        self.paramChange.setObjectName(_fromUtf8("paramChange"))
        self.widget1 = QtGui.QWidget(self.tab_3)
        self.widget1.setGeometry(QtCore.QRect(20, 10, 381, 22))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_8 = QtGui.QLabel(self.widget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.paramKeyEidt = QtGui.QLineEdit(self.widget1)
        self.paramKeyEidt.setObjectName(_fromUtf8("paramKeyEidt"))
        self.horizontalLayout_2.addWidget(self.paramKeyEidt)
        self.label_7 = QtGui.QLabel(self.widget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.paramValueEidt = QtGui.QLineEdit(self.widget1)
        self.paramValueEidt.setObjectName(_fromUtf8("paramValueEidt"))
        self.horizontalLayout_2.addWidget(self.paramValueEidt)
        self.propertyWidget.addTab(self.tab_3, _fromUtf8(""))
        self.propertyButton = QtGui.QPushButton(Form)
        self.propertyButton.setGeometry(QtCore.QRect(310, 450, 75, 23))
        self.propertyButton.setObjectName(_fromUtf8("propertyButton"))
        self.closeButton = QtGui.QPushButton(Form)
        self.closeButton.setGeometry(QtCore.QRect(400, 450, 75, 23))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.widget2 = QtGui.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(40, 400, 431, 25))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.getButton = QtGui.QPushButton(self.widget2)
        self.getButton.setObjectName(_fromUtf8("getButton"))
        self.horizontalLayout.addWidget(self.getButton)
        self.postButton = QtGui.QPushButton(self.widget2)
        self.postButton.setObjectName(_fromUtf8("postButton"))
        self.horizontalLayout.addWidget(self.postButton)
        self.putButton = QtGui.QPushButton(self.widget2)
        self.putButton.setObjectName(_fromUtf8("putButton"))
        self.horizontalLayout.addWidget(self.putButton)
        self.deleteButton = QtGui.QPushButton(self.widget2)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.horizontalLayout.addWidget(self.deleteButton)

        self.retranslateUi(Form)
        self.propertyWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "url:", None))
        self.label_2.setText(_translate("Form", "file:", None))
        self.contentFileBrowser.setText(_translate("Form", "browser", None))
        self.label_4.setText(_translate("Form", "Ctt:", None))
        self.propertyWidget.setTabText(self.propertyWidget.indexOf(self.tab), _translate("Form", "Content", None))
        self.headersAdd.setText(_translate("Form", "add", None))
        self.headersRemove.setText(_translate("Form", "remove", None))
        self.headersChange.setText(_translate("Form", "change", None))
        self.label_5.setText(_translate("Form", "Key", None))
        self.label_6.setText(_translate("Form", "value", None))
        self.propertyWidget.setTabText(self.propertyWidget.indexOf(self.tab_2), _translate("Form", "Headers", None))
        self.paramAdd.setText(_translate("Form", "add", None))
        self.paramRemove.setText(_translate("Form", "remove", None))
        self.paramChange.setText(_translate("Form", "change", None))
        self.label_8.setText(_translate("Form", "Key", None))
        self.label_7.setText(_translate("Form", "value", None))
        self.propertyWidget.setTabText(self.propertyWidget.indexOf(self.tab_3), _translate("Form", "Paramenter", None))
        self.propertyButton.setText(_translate("Form", "Property", None))
        self.closeButton.setText(_translate("Form", "Close", None))
        self.getButton.setText(_translate("Form", "GET", None))
        self.postButton.setText(_translate("Form", "POST", None))
        self.putButton.setText(_translate("Form", "PUT", None))
        self.deleteButton.setText(_translate("Form", "DELETE", None))

